language: python

python:
  - 2.7
  - 3.4

env:
  - DJANGO_VERSION='<1.8,>=1.7'
  - DJANGO_VERSION='<1.9,>=1.8'

before_install: pip install coverage codecov

install: pip install -U Django$DJANGO_VERSION

script: coverage run --source=djublog,tests setup.py test

after_success: codecov
